name: Deploy edge

on:
  schedule:
    - cron: '0 6 * * *' # At 06:00
  push:
    branches:
      - main
    paths:
      # Workflow file itself
      - '.github/workflows/deploy_edge.yml'
      - '.github/workflows/build-and-push.yml'
      # Dockerfile
      - '**/Dockerfile'
  workflow_dispatch:

permissions:
  attestations: write
  contents: read
  id-token: write
  packages: write

jobs:
  push_to_registry:
    name: Push edge

    strategy:
      fail-fast: false

    uses: ./.github/workflows/build-and-push.yml
    with:
      version: master
      tag: edge
      latest: false
      latest_major: false
      latest_minor: false
      latest_patch: false
    secrets: inherit
