name: Deploy release

on:
  schedule:
    - cron: '0 0 * * 1' # At 00:00 on Monday
  push:
    branches:
      - main
    paths:
      # Workflow file itself
      - '.github/workflows/deploy_release.yml'
      # Dockerfile
      - '**/Dockerfile'
  workflow_dispatch:

permissions:
  attestations: write
  contents: read
  id-token: write
  packages: write

jobs:
  push_to_registry:
    name: Push release
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4.1.5

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5.5.1
        with:
          # list of Docker images to use as base name for tags
          images: |
            ams21/cmake
            ghcr.io/ams21/cmake
          flavor: |
            latest=false
            prefix=
            suffix=
          # generate Docker tags based on the following events/attributes
          tags: |
            type=raw,value=release

      - name: Docker Setup QEMU
        uses: docker/setup-qemu-action@v3.0.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.3.0

      - name: Log in to Docker Hub
        uses: docker/login-action@v3.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3.1.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v5.3.0
        with:
          context: ./
          build-args: "VERSION=release"
          push: true
          platforms: "linux/386,linux/amd64,linux/arm,linux/arm64"
          annotations: ${{ steps.meta.outputs.annotations }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Attest Docker Hub
        uses: actions/attest-build-provenance@v1.1.2
        with:
          subject-name: index.docker.io/ams21/cmake
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true

      - name: Attest GitHub Container Registry
        uses: actions/attest-build-provenance@v1.1.2
        with:
          subject-name: ghcr.io/ams21/cmake
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true
