name: Deploy release

on:
  schedule:
    - cron: '0 0 * * 1' # At 00:00 on Monday
  push:
    branches:
      - main
    paths:
      # Workflow file itself
      - '.github/workflows/deploy_release.yml'
      - '.github/workflows/build-and-push.yml'
      # Dockerfile
      - '**/Dockerfile'
  workflow_dispatch:

permissions:
  attestations: write
  contents: read
  id-token: write
  packages: write

jobs:
  push_to_registry:
    name: Push release

    strategy:
      fail-fast: false
    uses: ./.github/workflows/build-and-push.yml
    with:
      version: release
      tag: release
      latest: false
      latest_major: false
      latest_minor: false
      latest_patch: false
    secrets: inherit
